// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4914.TestBot;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.Spark;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.VictorSP;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
	
    public static VictorSP leftDouble;
    public static VictorSP leftSingle;
    public static VictorSP rightDouble;
    public static VictorSP rightSingle;
    
	public static void init() {
		
		// Drivetrain
		
		leftDouble = new VictorSP(8);
		leftDouble.setInverted(false);
		
		leftSingle = new VictorSP(9);
		leftSingle.setInverted(false);
		
		rightDouble = new VictorSP(5);
		rightDouble.setInverted(true);
		
		rightSingle = new VictorSP(3);
		rightSingle.setInverted(true);
    }
}
